# Generated by Django 2.2.3 on 2019-07-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('IMEI_no', models.IntegerField()),
                ('is_engaged', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS')], max_length=1)),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
